### ISSUE TITLE
Planka REST API question.

### ISSUE THREAD

**Issue by sa6kad** [hwelch-fle/plankapy#2]
Hi. Great work that can be used as a basis for other projects.
Where did you find Planka REST API documentation? 

Thanks.

**Comment by decole** [comment]
So I find rest entrypoints in https://github.com/plankanban/planka/blob/master/server/config/routes.js
and watch behavior in websocet by planka web page

**Comment by sa6kad** [comment]
> So I find rest entrypoints in https://github.com/plankanban/planka/blob/master/server/config/routes.js and watch behavior in websocet by planka web page.
> 
> I am not the owner of the project, but as far as I know, he used this file https://github.com/plankanban/planka/blob/master/server/config/routes.js

Thanks a lot for the answer.
